name: Terraform Format, Validate & Plan

on:
  workflow_run:
    workflows: ["Update Lambda Function"]   # Name of the workflow that updates Lambda
    types:
      - completed
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Lint & Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183969845:role/github-assume-role
          role-session-name: github-actions-session
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/envs/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform/envs/dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform/envs/dev
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/envs/dev