name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        type: choice
        options:
        - dev
        - staging
        - prod
      confirm_destroy:
        description: 'Type "DESTROY" to confirm'
        required: true
        type: string
      destroy_ecr:
        description: 'Also destroy ECR repository (will delete all images)'
        required: false
        default: false
        type: boolean

env:
  AWS_REGION: ap-south-1
  AWS_ROLE_ARN: arn:aws:iam::436450225331:role/oidc-assume-role 

permissions:
  id-token: write
  contents: read

jobs:
  destroy-infrastructure:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    if: github.event.inputs.confirm_destroy == 'DESTROY'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-Destroy-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0
          terraform_wrapper: false

      - name: Destroy Main Infrastructure
        working-directory: terraform/environments/${{ github.event.inputs.environment }}
        run: |
          terraform init
          terraform destroy -auto-approve \
            -var="aws_region=${{ env.AWS_REGION }}"

      - name: Destroy ECR Repository
        if: github.event.inputs.destroy_ecr == 'true'
        working-directory: terraform/modules/ecr
        run: |
          terraform init
          terraform destroy -auto-approve \
            -var="project_name=hello-world-lambda" \
            -var="environment=${{ github.event.inputs.environment }}" \
            -var="aws_region=${{ env.AWS_REGION }}"